// Code generated by "stringer -type=JKErrorCode"; DO NOT EDIT.

package jkerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownErr - -1]
	_ = x[InitParseFailed-10001]
	_ = x[InitParamTypeErr-20001]
	_ = x[ExceptObject-20002]
	_ = x[PathIllegalErr-30001]
	_ = x[IterAllKeyErr-30002]
	_ = x[ExcludePathErr-30003]
}

const (
	_JKErrorCode_name_0 = "UnknownErr"
	_JKErrorCode_name_1 = "InitParseFailed"
	_JKErrorCode_name_2 = "InitParamTypeErrExceptObject"
	_JKErrorCode_name_3 = "PathIllegalErrIterAllKeyErrExcludePathErr"
)

var (
	_JKErrorCode_index_2 = [...]uint8{0, 16, 28}
	_JKErrorCode_index_3 = [...]uint8{0, 14, 27, 41}
)

func (i JKErrorCode) String() string {
	switch {
	case i == -1:
		return _JKErrorCode_name_0
	case i == 10001:
		return _JKErrorCode_name_1
	case 20001 <= i && i <= 20002:
		i -= 20001
		return _JKErrorCode_name_2[_JKErrorCode_index_2[i]:_JKErrorCode_index_2[i+1]]
	case 30001 <= i && i <= 30003:
		i -= 30001
		return _JKErrorCode_name_3[_JKErrorCode_index_3[i]:_JKErrorCode_index_3[i+1]]
	default:
		return "JKErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
